up:
	docker compose up --build -d

down:
	docker compose down

build:
	docker compose build --no-cache

logs:
	docker compose logs -f

backend-dev:
	cd backend && npm run dev

frontend-dev:
	cd frontend && npm run dev

mongo-logs:
	docker compose logs -f mongo
